<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>The logistic regression on loan’s report</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' || rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">FGV MBA</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="01_exploration_report.html">Exploration</a>
</li>
<li>
  <a href="02_logistic_regression_report.html">Loan Logistic Regression</a>
</li>
<li>
  <a href="03_conclusion.html">Conclusion</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">The logistic regression on loan’s report</h1>
<h4 class="date">July, 2019</h4>

</div>

<div id="TOC">
<ul>
<li><a href="#objective"><span class="toc-section-number">1</span> Objective</a></li>
<li><a href="#task-description"><span class="toc-section-number">2</span> Task description</a><ul>
<li><a href="#dataset-preparation"><span class="toc-section-number">2.1</span> Dataset preparation</a></li>
<li><a href="#variable-selection"><span class="toc-section-number">2.2</span> Variable selection</a></li>
<li><a href="#investigating-multicollinearity"><span class="toc-section-number">2.3</span> Investigating Multicollinearity</a></li>
<li><a href="#sample-split-into-test-and-training-data"><span class="toc-section-number">2.4</span> Sample split into Test and Training Data</a></li>
<li><a href="#fit-the-logistic-model"><span class="toc-section-number">2.5</span> Fit the logistic model</a></li>
</ul></li>
<li><a href="#evaluating-the-model-performance"><span class="toc-section-number">3</span> Evaluating the model performance</a></li>
</ul>
</div>

<div id="objective" class="section level1">
<h1><span class="header-section-number">1</span> Objective</h1>
<p>The goal of this report is trying to fit a logistic regression model on Loan data aiming to predict the probability of delinquency for each contract.</p>
</div>
<div id="task-description" class="section level1">
<h1><span class="header-section-number">2</span> Task description</h1>
<div id="dataset-preparation" class="section level2">
<h2><span class="header-section-number">2.1</span> Dataset preparation</h2>
<p>Using the vanilla transaction dataset, we calculated several derived variables for each account.</p>
<p>First, we calculated an additional table with the current account balance and average account balance of each account.</p>
<p>Later on, we calculated another auxiliary table that contains the proportion of each kind of transaction (k_symbol) for each account. The idea of these variable is to capture the spend pattern of each client.</p>
<p>Finally, we combine the 682 Loan Contracts observations with client, district, credit card and the auxiliary tables we calculated early.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1">temp &lt;-<span class="st"> </span><span class="kw">left_join</span>(loan, disposition, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&#39;account_id&#39;</span>, <span class="st">&#39;type&#39;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-2" title="2"><span class="st">  </span><span class="kw">left_join</span>(client, <span class="dt">by =</span> <span class="st">&#39;client_id&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-3" title="3"><span class="st">  </span><span class="kw">left_join</span>(district, <span class="dt">by =</span> <span class="st">&#39;district_id&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-4" title="4"><span class="st">  </span><span class="kw">left_join</span>(creditcard, <span class="dt">by =</span> <span class="st">&#39;disp_id&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-5" title="5"><span class="st">  </span><span class="kw">left_join</span>(account_balance, <span class="dt">by =</span> <span class="st">&#39;account_id&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-6" title="6"><span class="st">  </span><span class="kw">left_join</span>(account_transaction_pattern, <span class="dt">by =</span> <span class="st">&#39;account_id&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">card_age_month =</span> (issued <span class="op">%--%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-8" title="8"><span class="st">                             </span><span class="kw">make_date</span>(<span class="dv">1998</span>, <span class="dv">12</span>, <span class="dv">31</span>)) <span class="op">/</span><span class="st"> </span><span class="kw">months</span>(<span class="dv">1</span>),</a>
<a class="sourceLine" id="cb1-9" title="9">         <span class="dt">last_transaction_age_days =</span> ((last_transaction_date.y <span class="op">%--%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-10" title="10"><span class="st">                                         </span><span class="kw">make_date</span>(<span class="dv">1998</span>, <span class="dv">12</span>, <span class="dv">31</span>)) <span class="op">/</span><span class="st"> </span><span class="kw">days</span>(<span class="dv">1</span>)),</a>
<a class="sourceLine" id="cb1-11" title="11">         <span class="dt">has_card =</span> <span class="kw">ifelse</span>(type.y <span class="op">==</span><span class="st"> &#39;no card&#39;</span>, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-12" title="12"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">c</span>(<span class="st">&quot;amount.x&quot;</span>, <span class="st">&quot;duration&quot;</span>, <span class="st">&quot;payments&quot;</span>, <span class="st">&quot;status&quot;</span>, <span class="st">&quot;defaulter&quot;</span>, </a>
<a class="sourceLine" id="cb1-13" title="13">                  <span class="st">&quot;contract_status&quot;</span>, <span class="st">&quot;gender&quot;</span>, <span class="st">&quot;age&quot;</span>, <span class="st">&quot;district_name&quot;</span>, </a>
<a class="sourceLine" id="cb1-14" title="14">                  <span class="st">&quot;region&quot;</span>, <span class="st">&quot;no_of_inhabitants&quot;</span>, </a>
<a class="sourceLine" id="cb1-15" title="15">                  <span class="st">&quot;no_of_municip_inhabitants_less_499&quot;</span>, </a>
<a class="sourceLine" id="cb1-16" title="16">                  <span class="st">&quot;no_of_municip_500_to_1999&quot;</span>, <span class="st">&quot;no_of_municip_2000_to_9999&quot;</span>, </a>
<a class="sourceLine" id="cb1-17" title="17">                  <span class="st">&quot;no_of_municip_greater_10000&quot;</span>, <span class="st">&quot;no_of_cities&quot;</span>, </a>
<a class="sourceLine" id="cb1-18" title="18">                  <span class="st">&quot;ratio_of_urban_inhabitants&quot;</span>, </a>
<a class="sourceLine" id="cb1-19" title="19">                  <span class="st">&quot;average_salary&quot;</span>, <span class="st">&quot;unemploymant_rate_1995&quot;</span>, </a>
<a class="sourceLine" id="cb1-20" title="20">                  <span class="st">&quot;unemploymant_rate_1996&quot;</span>, </a>
<a class="sourceLine" id="cb1-21" title="21">                  <span class="st">&quot;no_of_enterpreneurs_per_1000_inhabitants&quot;</span>, </a>
<a class="sourceLine" id="cb1-22" title="22">                  <span class="st">&quot;no_of_commited_crimes_1995&quot;</span>, </a>
<a class="sourceLine" id="cb1-23" title="23">                  <span class="st">&quot;no_of_commited_crimes_1996&quot;</span>, <span class="st">&quot;type.y&quot;</span>, </a>
<a class="sourceLine" id="cb1-24" title="24">                  <span class="st">&quot;card_age_month&quot;</span>,<span class="st">&quot;account_balance&quot;</span>, </a>
<a class="sourceLine" id="cb1-25" title="25">                  <span class="st">&quot;avg_balance&quot;</span>,<span class="st">&quot;transaction_count&quot;</span>, <span class="st">&quot;amount.y&quot;</span>, </a>
<a class="sourceLine" id="cb1-26" title="26">                  <span class="st">&quot;last_transaction_age_days&quot;</span>, <span class="st">&quot;prop_old_age_pension&quot;</span>, </a>
<a class="sourceLine" id="cb1-27" title="27">                  <span class="st">&quot;prop_insurance_payment&quot;</span>, </a>
<a class="sourceLine" id="cb1-28" title="28">                  <span class="st">&quot;prop_sanction_interest&quot;</span>,<span class="st">&quot;prop_household&quot;</span>, </a>
<a class="sourceLine" id="cb1-29" title="29">                  <span class="st">&quot;prop_statement&quot;</span>, <span class="st">&quot;prop_interest_credited&quot;</span>, </a>
<a class="sourceLine" id="cb1-30" title="30">                  <span class="st">&quot;prop_loan_payment&quot;</span>, <span class="st">&quot;prop_other&quot;</span>, <span class="st">&quot;has_card&quot;</span>))</a>
<a class="sourceLine" id="cb1-31" title="31"></a>
<a class="sourceLine" id="cb1-32" title="32"><span class="kw">colnames</span>(temp) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;x_loan_amount&quot;</span>, <span class="st">&quot;x_loan_duration&quot;</span>, <span class="st">&quot;x_loan_payments&quot;</span>, </a>
<a class="sourceLine" id="cb1-33" title="33">                    <span class="st">&quot;x_loan_status&quot;</span>, <span class="st">&quot;y_loan_defaulter&quot;</span>, <span class="st">&quot;x_loan_contract_status&quot;</span>,</a>
<a class="sourceLine" id="cb1-34" title="34">                    <span class="st">&quot;x_client_gender&quot;</span>, <span class="st">&quot;x_client_age&quot;</span>, </a>
<a class="sourceLine" id="cb1-35" title="35">                    <span class="st">&quot;x_district_name&quot;</span>, <span class="st">&quot;x_region&quot;</span>, </a>
<a class="sourceLine" id="cb1-36" title="36">                    <span class="st">&quot;x_no_of_inhabitants&quot;</span>, <span class="st">&quot;x_no_of_municip_inhabitants_less_499&quot;</span>, </a>
<a class="sourceLine" id="cb1-37" title="37">                    <span class="st">&quot;x_no_of_municip_500_to_1999&quot;</span>, <span class="st">&quot;x_no_of_municip_2000_to_9999&quot;</span>, </a>
<a class="sourceLine" id="cb1-38" title="38">                    <span class="st">&quot;x_no_of_municip_greater_10000&quot;</span>, <span class="st">&quot;x_no_of_cities&quot;</span>, </a>
<a class="sourceLine" id="cb1-39" title="39">                    <span class="st">&quot;x_ratio_of_urban_inhabitants&quot;</span>, </a>
<a class="sourceLine" id="cb1-40" title="40">                    <span class="st">&quot;x_average_salary&quot;</span>, <span class="st">&quot;x_unemploymant_rate_1995&quot;</span>, </a>
<a class="sourceLine" id="cb1-41" title="41">                    <span class="st">&quot;x_unemploymant_rate_1996&quot;</span>, </a>
<a class="sourceLine" id="cb1-42" title="42">                    <span class="st">&quot;x_no_of_enterpreneurs_per_1000_inhabitants&quot;</span>, </a>
<a class="sourceLine" id="cb1-43" title="43">                    <span class="st">&quot;x_no_of_commited_crimes_1995&quot;</span>, </a>
<a class="sourceLine" id="cb1-44" title="44">                    <span class="st">&quot;x_no_of_commited_crimes_1996&quot;</span>, <span class="st">&quot;x_card_type&quot;</span>, </a>
<a class="sourceLine" id="cb1-45" title="45">                    <span class="st">&quot;x_card_age_month&quot;</span>,<span class="st">&quot;x_account_balance&quot;</span>, </a>
<a class="sourceLine" id="cb1-46" title="46">                    <span class="st">&quot;x_avg_account_balance&quot;</span>,<span class="st">&quot;x_transaction_count&quot;</span>, </a>
<a class="sourceLine" id="cb1-47" title="47">                    <span class="st">&quot;x_transaction_amount&quot;</span>, <span class="st">&quot;x_last_transaction_age_days&quot;</span>, </a>
<a class="sourceLine" id="cb1-48" title="48">                    <span class="st">&quot;x_prop_old_age_pension&quot;</span>, <span class="st">&quot;x_prop_insurance_payment&quot;</span>, </a>
<a class="sourceLine" id="cb1-49" title="49">                    <span class="st">&quot;x_prop_sanction_interest&quot;</span>,<span class="st">&quot;x_prop_household&quot;</span>,<span class="st">&quot;x_prop_statement&quot;</span>,</a>
<a class="sourceLine" id="cb1-50" title="50">                    <span class="st">&quot;x_prop_interest_credited&quot;</span>, <span class="st">&quot;x_prop_loan_payment&quot;</span>, <span class="st">&quot;x_prop_other&quot;</span>,</a>
<a class="sourceLine" id="cb1-51" title="51">                    <span class="st">&quot;x_has_card&quot;</span>)</a>
<a class="sourceLine" id="cb1-52" title="52"></a>
<a class="sourceLine" id="cb1-53" title="53">temp &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(temp, y_loan_defaulter, <span class="kw">everything</span>())</a>
<a class="sourceLine" id="cb1-54" title="54"></a>
<a class="sourceLine" id="cb1-55" title="55">temp<span class="op">$</span>x_card_type =<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(temp<span class="op">$</span>x_card_type), <span class="st">&#39;no card&#39;</span>, </a>
<a class="sourceLine" id="cb1-56" title="56">                          <span class="kw">as.character</span>(temp<span class="op">$</span>x_card_type))</a>
<a class="sourceLine" id="cb1-57" title="57"></a>
<a class="sourceLine" id="cb1-58" title="58">temp<span class="op">$</span>x_has_card =<span class="st"> </span><span class="kw">ifelse</span>(temp<span class="op">$</span>x_card_type <span class="op">==</span><span class="st"> &#39;no card&#39;</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb1-59" title="59"></a>
<a class="sourceLine" id="cb1-60" title="60">temp<span class="op">$</span>x_card_age_month =<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(temp<span class="op">$</span>x_card_age_month), <span class="dv">0</span>, </a>
<a class="sourceLine" id="cb1-61" title="61">                               temp<span class="op">$</span>x_card_age_month)</a>
<a class="sourceLine" id="cb1-62" title="62"></a>
<a class="sourceLine" id="cb1-63" title="63">temp<span class="op">$</span>y_loan_defaulter =<span class="st"> </span><span class="kw">as.numeric</span>(temp<span class="op">$</span>y_loan_defaulter)</a></code></pre></div>
<p>We ended up having a data set with 39 variables.</p>
<table>
<thead>
<tr class="header">
<th align="left">variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">y_loan_defaulter</td>
</tr>
<tr class="even">
<td align="left">x_loan_amount</td>
</tr>
<tr class="odd">
<td align="left">x_loan_duration</td>
</tr>
<tr class="even">
<td align="left">x_loan_payments</td>
</tr>
<tr class="odd">
<td align="left">x_loan_status</td>
</tr>
<tr class="even">
<td align="left">x_loan_contract_status</td>
</tr>
<tr class="odd">
<td align="left">x_client_gender</td>
</tr>
<tr class="even">
<td align="left">x_client_age</td>
</tr>
<tr class="odd">
<td align="left">x_district_name</td>
</tr>
<tr class="even">
<td align="left">x_region</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_inhabitants</td>
</tr>
<tr class="even">
<td align="left">x_no_of_municip_inhabitants_less_499</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_municip_500_to_1999</td>
</tr>
<tr class="even">
<td align="left">x_no_of_municip_2000_to_9999</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_municip_greater_10000</td>
</tr>
<tr class="even">
<td align="left">x_no_of_cities</td>
</tr>
<tr class="odd">
<td align="left">x_ratio_of_urban_inhabitants</td>
</tr>
<tr class="even">
<td align="left">x_average_salary</td>
</tr>
<tr class="odd">
<td align="left">x_unemploymant_rate_1995</td>
</tr>
<tr class="even">
<td align="left">x_unemploymant_rate_1996</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_enterpreneurs_per_1000_inhabitants</td>
</tr>
<tr class="even">
<td align="left">x_no_of_commited_crimes_1995</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_commited_crimes_1996</td>
</tr>
<tr class="even">
<td align="left">x_card_type</td>
</tr>
<tr class="odd">
<td align="left">x_card_age_month</td>
</tr>
<tr class="even">
<td align="left">x_account_balance</td>
</tr>
<tr class="odd">
<td align="left">x_avg_account_balance</td>
</tr>
<tr class="even">
<td align="left">x_transaction_count</td>
</tr>
<tr class="odd">
<td align="left">x_transaction_amount</td>
</tr>
<tr class="even">
<td align="left">x_last_transaction_age_days</td>
</tr>
<tr class="odd">
<td align="left">x_prop_old_age_pension</td>
</tr>
<tr class="even">
<td align="left">x_prop_insurance_payment</td>
</tr>
<tr class="odd">
<td align="left">x_prop_sanction_interest</td>
</tr>
<tr class="even">
<td align="left">x_prop_household</td>
</tr>
<tr class="odd">
<td align="left">x_prop_statement</td>
</tr>
<tr class="even">
<td align="left">x_prop_interest_credited</td>
</tr>
<tr class="odd">
<td align="left">x_prop_loan_payment</td>
</tr>
<tr class="even">
<td align="left">x_prop_other</td>
</tr>
<tr class="odd">
<td align="left">x_has_card</td>
</tr>
</tbody>
</table>
</div>
<div id="variable-selection" class="section level2">
<h2><span class="header-section-number">2.2</span> Variable selection</h2>
<p>From this dataset, we excluded 6 variables that are redundant, shows no variability on the 682 Loan contract observations or have no applicability for the exercise:</p>
<ul>
<li><strong>x_prop_old_age_pension</strong> (no variation on selected sample);</li>
<li><strong>x_district_name</strong> (sample have not enough variability to fit a model);</li>
<li><strong>x_region</strong> (sample have not enough variability to fit a model);</li>
<li><strong>x_loan_status</strong> (redundant);</li>
<li><strong>x_loan_contract_status</strong> (redundant);</li>
<li><strong>x_prop_sanction_interest</strong> (seems not to be valid for this analysis, as the reason for interest payment in the account is exactly the delinquency in the observation contact itself).</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">temp &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(temp, <span class="op">-</span><span class="kw">c</span>(x_prop_old_age_pension, </a>
<a class="sourceLine" id="cb2-2" title="2">                               x_district_name, </a>
<a class="sourceLine" id="cb2-3" title="3">                               x_region, </a>
<a class="sourceLine" id="cb2-4" title="4">                               x_loan_status, </a>
<a class="sourceLine" id="cb2-5" title="5">                               x_loan_contract_status, </a>
<a class="sourceLine" id="cb2-6" title="6">                               x_prop_sanction_interest))</a></code></pre></div>
</div>
<div id="investigating-multicollinearity" class="section level2">
<h2><span class="header-section-number">2.3</span> Investigating Multicollinearity</h2>
<p>With the remaining variables we ran a multicollinearity test to identify additional variables to drop from the model specification.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">vars.quant &lt;-<span class="st"> </span><span class="kw">select_if</span>(temp, is.numeric)</a>
<a class="sourceLine" id="cb3-2" title="2">VIF &lt;-<span class="st"> </span><span class="kw">imcdiag</span>(vars.quant, temp<span class="op">$</span>y_loan_defaulter)</a>
<a class="sourceLine" id="cb3-3" title="3"></a>
<a class="sourceLine" id="cb3-4" title="4">VIF_Table_Before &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">variable =</span> <span class="kw">names</span>(VIF<span class="op">$</span>idiags[,<span class="dv">1</span>]),</a>
<a class="sourceLine" id="cb3-5" title="5">                    <span class="dt">VIF =</span> VIF<span class="op">$</span>idiags[,<span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb3-6" title="6"><span class="st">             </span><span class="kw">arrange</span>(<span class="kw">desc</span>(VIF))</a>
<a class="sourceLine" id="cb3-7" title="7"></a>
<a class="sourceLine" id="cb3-8" title="8"><span class="kw">kable</span>(VIF_Table_Before)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">x_no_of_inhabitants</td>
<td align="right">161.078688</td>
</tr>
<tr class="even">
<td align="left">x_prop_other</td>
<td align="right">156.614374</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_commited_crimes_1996</td>
<td align="right">153.788642</td>
</tr>
<tr class="even">
<td align="left">x_prop_household</td>
<td align="right">119.766648</td>
</tr>
<tr class="odd">
<td align="left">x_prop_interest_credited</td>
<td align="right">62.164451</td>
</tr>
<tr class="even">
<td align="left">x_prop_loan_payment</td>
<td align="right">42.215533</td>
</tr>
<tr class="odd">
<td align="left">x_prop_insurance_payment</td>
<td align="right">33.065760</td>
</tr>
<tr class="even">
<td align="left">x_transaction_amount</td>
<td align="right">13.077575</td>
</tr>
<tr class="odd">
<td align="left">x_prop_statement</td>
<td align="right">12.611010</td>
</tr>
<tr class="even">
<td align="left">x_transaction_count</td>
<td align="right">12.243487</td>
</tr>
<tr class="odd">
<td align="left">x_unemploymant_rate_1996</td>
<td align="right">11.942010</td>
</tr>
<tr class="even">
<td align="left">x_unemploymant_rate_1995</td>
<td align="right">11.457609</td>
</tr>
<tr class="odd">
<td align="left">x_average_salary</td>
<td align="right">10.592530</td>
</tr>
<tr class="even">
<td align="left">x_no_of_cities</td>
<td align="right">5.348665</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_enterpreneurs_per_1000_inhabitants</td>
<td align="right">4.398114</td>
</tr>
<tr class="even">
<td align="left">x_no_of_municip_2000_to_9999</td>
<td align="right">4.342691</td>
</tr>
<tr class="odd">
<td align="left">x_ratio_of_urban_inhabitants</td>
<td align="right">4.141633</td>
</tr>
<tr class="even">
<td align="left">x_loan_amount</td>
<td align="right">3.656975</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_municip_500_to_1999</td>
<td align="right">3.494354</td>
</tr>
<tr class="even">
<td align="left">x_loan_payments</td>
<td align="right">3.467355</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_commited_crimes_1995</td>
<td align="right">3.343160</td>
</tr>
<tr class="even">
<td align="left">x_no_of_municip_greater_10000</td>
<td align="right">2.784531</td>
</tr>
<tr class="odd">
<td align="left">x_loan_duration</td>
<td align="right">2.634738</td>
</tr>
<tr class="even">
<td align="left">x_has_card</td>
<td align="right">2.365295</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_municip_inhabitants_less_499</td>
<td align="right">2.353720</td>
</tr>
<tr class="even">
<td align="left">x_card_age_month</td>
<td align="right">2.200021</td>
</tr>
<tr class="odd">
<td align="left">x_avg_account_balance</td>
<td align="right">1.842499</td>
</tr>
<tr class="even">
<td align="left">y_loan_defaulter</td>
<td align="right">1.728511</td>
</tr>
<tr class="odd">
<td align="left">x_account_balance</td>
<td align="right">1.422176</td>
</tr>
<tr class="even">
<td align="left">x_last_transaction_age_days</td>
<td align="right">1.068578</td>
</tr>
<tr class="odd">
<td align="left">x_client_age</td>
<td align="right">1.053711</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">ggplot</span>(VIF_Table_Before, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">fct_reorder</span>(variable, VIF), <span class="dt">y =</span> <span class="kw">log</span>(VIF), <span class="dt">label =</span> <span class="kw">round</span>(VIF, <span class="dv">2</span>))) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">stat=</span><span class="st">&#39;identity&#39;</span>, <span class="dt">fill=</span><span class="st">&quot;black&quot;</span>, <span class="dt">size=</span><span class="dv">15</span>)  <span class="op">+</span></a>
<a class="sourceLine" id="cb4-3" title="3"><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="dv">0</span>, </a>
<a class="sourceLine" id="cb4-4" title="4">                   <span class="dt">yend =</span> <span class="kw">log</span>(VIF), </a>
<a class="sourceLine" id="cb4-5" title="5">                   <span class="dt">xend =</span> variable), </a>
<a class="sourceLine" id="cb4-6" title="6">               <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb4-7" title="7"><span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb4-8" title="8"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="kw">log</span>(<span class="dv">5</span>)), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb4-9" title="9"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="ot">NULL</span>, <span class="dt">breaks =</span> <span class="ot">NULL</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb4-10" title="10"><span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb4-11" title="11"><span class="st">  </span><span class="kw">theme_economist</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb4-12" title="12"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&#39;none&#39;</span>, </a>
<a class="sourceLine" id="cb4-13" title="13">        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(), </a>
<a class="sourceLine" id="cb4-14" title="14">        <span class="dt">panel.grid.minor =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></a>
<a class="sourceLine" id="cb4-15" title="15"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Variable&#39;</span>,</a>
<a class="sourceLine" id="cb4-16" title="16">       <span class="dt">y =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb4-17" title="17">       <span class="dt">title =</span> <span class="st">&#39;Variance Inflation Factor&#39;</span>,</a>
<a class="sourceLine" id="cb4-18" title="18">       <span class="dt">subtitle=</span><span class="st">&quot;Checking for multicolinearity in X&#39;s variables.</span></a>
<a class="sourceLine" id="cb4-19" title="19"><span class="st">       Variables with VIF more than 5 will </span></a>
<a class="sourceLine" id="cb4-20" title="20"><span class="st">       be droped from the model&quot;</span>)</a></code></pre></div>
<p><img src="02_logistic_regression_report_files/figure-html/plot_correl-1.png" width="100%" /></p>
<p>We decided to exclude any variable with a VIF greater than 5.</p>
<p>Below variables were excluded based on the multicollinear presence on them.</p>
<ul>
<li><strong>x_prop_insurance_payment</strong>;</li>
<li><strong>x_prop_household</strong>;</li>
<li><strong>x_prop_statement</strong> ;</li>
<li><strong>x_prop_loan_payment</strong>;</li>
<li><strong>x_prop_other</strong>;</li>
<li><strong>x_no_of_inhabitants</strong>;</li>
<li><strong>x_no_of_commited_crimes_1996</strong>;</li>
<li><strong>x_transaction_amount</strong>;</li>
<li><strong>x_transaction_count</strong>;</li>
<li><strong>x_unemploymant_rate_1996</strong>;</li>
<li><strong>x_unemploymant_rate_1995</strong>;</li>
<li><strong>x_average_salary</strong>;</li>
<li><strong>x_no_of_cities</strong>.</li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1">temp &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(temp, <span class="op">-</span><span class="kw">c</span>(x_prop_insurance_payment,</a>
<a class="sourceLine" id="cb5-2" title="2">                               x_prop_household,</a>
<a class="sourceLine" id="cb5-3" title="3">                               x_prop_statement,</a>
<a class="sourceLine" id="cb5-4" title="4">                               x_prop_loan_payment,</a>
<a class="sourceLine" id="cb5-5" title="5">                               x_prop_other,</a>
<a class="sourceLine" id="cb5-6" title="6">                               x_no_of_inhabitants,</a>
<a class="sourceLine" id="cb5-7" title="7">                               x_no_of_commited_crimes_<span class="dv">1996</span>,</a>
<a class="sourceLine" id="cb5-8" title="8">                               x_transaction_amount,</a>
<a class="sourceLine" id="cb5-9" title="9">                               x_transaction_count,</a>
<a class="sourceLine" id="cb5-10" title="10">                               x_unemploymant_rate_<span class="dv">1996</span>,</a>
<a class="sourceLine" id="cb5-11" title="11">                               x_unemploymant_rate_<span class="dv">1995</span>,</a>
<a class="sourceLine" id="cb5-12" title="12">                               x_average_salary,</a>
<a class="sourceLine" id="cb5-13" title="13">                               x_no_of_cities))</a>
<a class="sourceLine" id="cb5-14" title="14"></a>
<a class="sourceLine" id="cb5-15" title="15">loan_reg_dataset &lt;-<span class="st"> </span>temp</a></code></pre></div>
<p>Here is the final correlation matrix we got:</p>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">x_loan_amount</td>
<td align="right">3.576281</td>
</tr>
<tr class="even">
<td align="left">x_no_of_municip_500_to_1999</td>
<td align="right">2.781569</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_municip_2000_to_9999</td>
<td align="right">2.565167</td>
</tr>
<tr class="even">
<td align="left">x_loan_duration</td>
<td align="right">2.366083</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_enterpreneurs_per_1000_inhabitants</td>
<td align="right">2.289033</td>
</tr>
<tr class="even">
<td align="left">x_has_card</td>
<td align="right">2.242915</td>
</tr>
<tr class="odd">
<td align="left">x_loan_payments</td>
<td align="right">2.208547</td>
</tr>
<tr class="even">
<td align="left">x_no_of_municip_greater_10000</td>
<td align="right">2.147182</td>
</tr>
<tr class="odd">
<td align="left">x_card_age_month</td>
<td align="right">2.028568</td>
</tr>
<tr class="even">
<td align="left">x_ratio_of_urban_inhabitants</td>
<td align="right">1.986178</td>
</tr>
<tr class="odd">
<td align="left">x_no_of_municip_inhabitants_less_499</td>
<td align="right">1.881482</td>
</tr>
<tr class="even">
<td align="left">x_no_of_commited_crimes_1995</td>
<td align="right">1.798576</td>
</tr>
<tr class="odd">
<td align="left">x_avg_account_balance</td>
<td align="right">1.656011</td>
</tr>
<tr class="even">
<td align="left">x_account_balance</td>
<td align="right">1.378326</td>
</tr>
<tr class="odd">
<td align="left">x_prop_interest_credited</td>
<td align="right">1.280158</td>
</tr>
<tr class="even">
<td align="left">y_loan_defaulter</td>
<td align="right">1.242373</td>
</tr>
<tr class="odd">
<td align="left">x_last_transaction_age_days</td>
<td align="right">1.048220</td>
</tr>
<tr class="even">
<td align="left">x_client_age</td>
<td align="right">1.040390</td>
</tr>
</tbody>
</table>
<p>Plot of VIF values:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">ggplot</span>(VIF_Table_After, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">fct_reorder</span>(variable, VIF), <span class="dt">y =</span> <span class="kw">log</span>(VIF), <span class="dt">label =</span> <span class="kw">round</span>(VIF, <span class="dv">2</span>))) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb6-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">stat=</span><span class="st">&#39;identity&#39;</span>, <span class="dt">fill=</span><span class="st">&quot;black&quot;</span>, <span class="dt">size=</span><span class="dv">15</span>)  <span class="op">+</span></a>
<a class="sourceLine" id="cb6-3" title="3"><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="dv">0</span>, </a>
<a class="sourceLine" id="cb6-4" title="4">                   <span class="dt">yend =</span> <span class="kw">log</span>(VIF), </a>
<a class="sourceLine" id="cb6-5" title="5">                   <span class="dt">xend =</span> variable), </a>
<a class="sourceLine" id="cb6-6" title="6">               <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-7" title="7"><span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">size=</span><span class="dv">4</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-8" title="8"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="kw">log</span>(<span class="dv">5</span>)), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-9" title="9"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="ot">NULL</span>, <span class="dt">breaks =</span> <span class="ot">NULL</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-10" title="10"><span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb6-11" title="11"><span class="st">  </span><span class="kw">theme_economist</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb6-12" title="12"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&#39;none&#39;</span>, </a>
<a class="sourceLine" id="cb6-13" title="13">        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(), </a>
<a class="sourceLine" id="cb6-14" title="14">        <span class="dt">panel.grid.minor =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></a>
<a class="sourceLine" id="cb6-15" title="15"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Variable&#39;</span>,</a>
<a class="sourceLine" id="cb6-16" title="16">       <span class="dt">y =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb6-17" title="17">       <span class="dt">title =</span> <span class="st">&#39;Variance Inflation Factor&#39;</span>,</a>
<a class="sourceLine" id="cb6-18" title="18">       <span class="dt">subtitle=</span><span class="st">&quot;Checking for multicolinearity in X&#39;s variables.</span></a>
<a class="sourceLine" id="cb6-19" title="19"><span class="st">       Variables with VIF more than 5 will </span></a>
<a class="sourceLine" id="cb6-20" title="20"><span class="st">       be droped from the model&quot;</span>)</a></code></pre></div>
<p><img src="02_logistic_regression_report_files/figure-html/plot_correl_2-1.png" width="100%" /></p>
<p>Correlation Matrix Plot: no Variable with correlation more than 0.6.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">cor_mtx &lt;-<span class="st"> </span><span class="kw">cor</span>(vars.quant)</a>
<a class="sourceLine" id="cb7-2" title="2"></a>
<a class="sourceLine" id="cb7-3" title="3"><span class="kw">ggcorrplot</span>(cor_mtx, <span class="dt">hc.order =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb7-4" title="4">           <span class="dt">type =</span> <span class="st">&quot;lower&quot;</span>, </a>
<a class="sourceLine" id="cb7-5" title="5">           <span class="dt">lab =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb7-6" title="6">           <span class="dt">lab_size =</span> <span class="dv">3</span>, </a>
<a class="sourceLine" id="cb7-7" title="7">           <span class="dt">method=</span><span class="st">&quot;circle&quot;</span>, </a>
<a class="sourceLine" id="cb7-8" title="8">           <span class="dt">colors =</span> <span class="kw">c</span>(<span class="st">&quot;tomato2&quot;</span>, <span class="st">&quot;white&quot;</span>, <span class="st">&quot;springgreen3&quot;</span>), </a>
<a class="sourceLine" id="cb7-9" title="9">           <span class="dt">title=</span><span class="st">&quot;Correlation Matrix of Loan Dataset&quot;</span>, </a>
<a class="sourceLine" id="cb7-10" title="10">           <span class="dt">ggtheme=</span>theme_bw)</a></code></pre></div>
<p><img src="02_logistic_regression_report_files/figure-html/plot_correl_3-1.png" width="100%" /></p>
</div>
<div id="sample-split-into-test-and-training-data" class="section level2">
<h2><span class="header-section-number">2.4</span> Sample split into Test and Training Data</h2>
<p>The available data in Loan Dataset is split into Train and Testing data on the following proportion:</p>
<ul>
<li><strong>Train Dataset</strong> (70% 478 obs);</li>
<li><strong>Test Dataset </strong> (30% 204 obs).</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">set.seed</span>(<span class="dv">12345</span>)</a>
<a class="sourceLine" id="cb8-2" title="2">index &lt;-<span class="st"> </span>caret<span class="op">::</span><span class="kw">createDataPartition</span>(loan_reg_dataset<span class="op">$</span>y_loan_defaulter, </a>
<a class="sourceLine" id="cb8-3" title="3">                                    <span class="dt">p=</span> <span class="fl">0.7</span>,<span class="dt">list =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb8-4" title="4"></a>
<a class="sourceLine" id="cb8-5" title="5">data.train &lt;-<span class="st"> </span>loan_reg_dataset[index, ]</a>
<a class="sourceLine" id="cb8-6" title="6">data.test  &lt;-<span class="st"> </span>loan_reg_dataset[<span class="op">-</span>index,]</a>
<a class="sourceLine" id="cb8-7" title="7"></a>
<a class="sourceLine" id="cb8-8" title="8"></a>
<a class="sourceLine" id="cb8-9" title="9">event_proportion &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="kw">prop.table</span>(<span class="kw">table</span>(loan_reg_dataset<span class="op">$</span>y_loan_defaulter)),</a>
<a class="sourceLine" id="cb8-10" title="10">                              <span class="kw">prop.table</span>(<span class="kw">table</span>(data.train<span class="op">$</span>y_loan_defaulter)),</a>
<a class="sourceLine" id="cb8-11" title="11">                              <span class="kw">prop.table</span>(<span class="kw">table</span>(data.test<span class="op">$</span>y_loan_defaulter)))</a>
<a class="sourceLine" id="cb8-12" title="12"></a>
<a class="sourceLine" id="cb8-13" title="13">event_proportion<span class="op">$</span>scope =<span class="st"> &#39;&#39;</span></a>
<a class="sourceLine" id="cb8-14" title="14">event_proportion<span class="op">$</span>scope[<span class="dv">1</span>] =<span class="st"> &#39;full dataset&#39;</span></a>
<a class="sourceLine" id="cb8-15" title="15">event_proportion<span class="op">$</span>scope[<span class="dv">2</span>] =<span class="st"> &#39;train dataset&#39;</span></a>
<a class="sourceLine" id="cb8-16" title="16">event_proportion<span class="op">$</span>scope[<span class="dv">3</span>] =<span class="st"> &#39;test dataset&#39;</span></a>
<a class="sourceLine" id="cb8-17" title="17"></a>
<a class="sourceLine" id="cb8-18" title="18">event_proportion &lt;-<span class="st"> </span><span class="kw">select</span>(event_proportion, scope, <span class="kw">everything</span>())</a>
<a class="sourceLine" id="cb8-19" title="19"></a>
<a class="sourceLine" id="cb8-20" title="20"><span class="kw">kable</span>(event_proportion)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">scope</th>
<th align="right">0</th>
<th align="right">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">full dataset</td>
<td align="right">0.8885630</td>
<td align="right">0.1114370</td>
</tr>
<tr class="even">
<td align="left">train dataset</td>
<td align="right">0.8933054</td>
<td align="right">0.1066946</td>
</tr>
<tr class="odd">
<td align="left">test dataset</td>
<td align="right">0.8774510</td>
<td align="right">0.1225490</td>
</tr>
</tbody>
</table>
<p>Both datasets keep the same proportion for the explained variable around 11%.</p>
</div>
<div id="fit-the-logistic-model" class="section level2">
<h2><span class="header-section-number">2.5</span> Fit the logistic model</h2>
<p>With the final cleaned dataset, we got from below steps we fit our Logistic Regression Y_loan_defaulter on all x variables.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">model_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="dt">data =</span> data.train, <span class="dt">formula =</span> y_loan_defaulter <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb9-2" title="2">                 <span class="dt">family=</span> <span class="kw">binomial</span>(<span class="dt">link=</span><span class="st">&#39;logit&#39;</span>))</a>
<a class="sourceLine" id="cb9-3" title="3"></a>
<a class="sourceLine" id="cb9-4" title="4"><span class="co"># jut truncating variable names to 30 char to fit nicely in the screen.</span></a>
<a class="sourceLine" id="cb9-5" title="5"><span class="kw">names</span>(model_<span class="dv">1</span><span class="op">$</span>coefficients) &lt;-<span class="st"> </span>stringr<span class="op">::</span><span class="kw">str_sub</span>(<span class="kw">names</span>(model_<span class="dv">1</span><span class="op">$</span>coefficients), <span class="dv">1</span>, <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb9-6" title="6"></a>
<a class="sourceLine" id="cb9-7" title="7"><span class="kw">summary</span>(model_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y_loan_defaulter ~ ., family = binomial(link = &quot;logit&quot;), 
##     data = data.train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5308  -0.4369  -0.2692  -0.1609   2.9273  
## 
## Coefficients: (1 not defined because of singularities)
##                                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                    -4.405e+00  2.351e+00  -1.874   0.0610 .  
## x_loan_amount                   7.239e-06  2.978e-06   2.431   0.0151 *  
## x_loan_duration                -2.860e-02  1.867e-02  -1.532   0.1255    
## x_loan_payments                 2.306e-03  1.839e-03   1.254   0.2099    
## x_client_gendermale             2.084e-02  3.594e-01   0.058   0.9537    
## x_client_age                    1.801e-02  1.414e-02   1.274   0.2028    
## x_no_of_municip_inhabitants_le -1.823e-03  6.599e-03  -0.276   0.7824    
## x_no_of_municip_500_to_1999     8.119e-04  1.957e-02   0.041   0.9669    
## x_no_of_municip_2000_to_9999   -1.178e-02  6.436e-02  -0.183   0.8547    
## x_no_of_municip_greater_10000  -3.642e-01  2.321e-01  -1.569   0.1167    
## x_ratio_of_urban_inhabitants    9.512e-03  1.150e-02   0.827   0.4080    
## x_no_of_enterpreneurs_per_1000 -1.078e-02  1.162e-02  -0.927   0.3538    
## x_no_of_commited_crimes_1995   -1.362e-02  9.617e-03  -1.416   0.1566    
## x_card_typegold                 5.329e-01  1.315e+00   0.405   0.6852    
## x_card_typejunior               3.728e-01  1.311e+00   0.284   0.7762    
## x_card_typeno card              1.580e+00  8.938e-01   1.768   0.0770 .  
## x_card_age_month                2.938e-02  3.072e-02   0.956   0.3390    
## x_account_balance               2.386e-06  1.383e-06   1.725   0.0844 .  
## x_avg_account_balance          -4.174e-06  2.969e-06  -1.406   0.1598    
## x_last_transaction_age_days     2.641e-02  4.276e-02   0.618   0.5368    
## x_prop_interest_credited        1.156e+01  2.241e+00   5.158  2.5e-07 ***
## x_has_card                             NA         NA      NA       NA    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 324.61  on 477  degrees of freedom
## Residual deviance: 246.59  on 457  degrees of freedom
## AIC: 288.59
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Alternatively we fit a second model only with variables statistically significant p-value less than 10%.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">model_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="dt">data =</span> data.train, <span class="dt">formula =</span> y_loan_defaulter <span class="op">~</span><span class="st"> </span>x_loan_amount <span class="op">+</span></a>
<a class="sourceLine" id="cb11-2" title="2"><span class="st">                 </span>x_loan_duration <span class="op">+</span><span class="st"> </span>x_has_card <span class="op">+</span><span class="st"> </span>x_prop_interest_credited,</a>
<a class="sourceLine" id="cb11-3" title="3">                 <span class="dt">family=</span> <span class="kw">binomial</span>(<span class="dt">link=</span><span class="st">&#39;logit&#39;</span>))</a>
<a class="sourceLine" id="cb11-4" title="4"></a>
<a class="sourceLine" id="cb11-5" title="5"><span class="co"># jut truncating variable names to 30 char to fit nicely in the screen.</span></a>
<a class="sourceLine" id="cb11-6" title="6"><span class="kw">names</span>(model_<span class="dv">2</span><span class="op">$</span>coefficients) &lt;-<span class="st"> </span>stringr<span class="op">::</span><span class="kw">str_sub</span>(<span class="kw">names</span>(model_<span class="dv">2</span><span class="op">$</span>coefficients), <span class="dv">1</span>, <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb11-7" title="7"></a>
<a class="sourceLine" id="cb11-8" title="8"><span class="kw">summary</span>(model_<span class="dv">2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y_loan_defaulter ~ x_loan_amount + x_loan_duration + 
##     x_has_card + x_prop_interest_credited, family = binomial(link = &quot;logit&quot;), 
##     data = data.train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5790  -0.4375  -0.3290  -0.2165   2.6686  
## 
## Coefficients:
##                            Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)              -3.632e+00  4.984e-01  -7.286 3.19e-13 ***
## x_loan_amount             9.023e-06  1.888e-06   4.780 1.75e-06 ***
## x_loan_duration          -3.864e-02  1.458e-02  -2.651  0.00803 ** 
## x_has_card               -1.064e+00  5.009e-01  -2.124  0.03364 *  
## x_prop_interest_credited  9.715e+00  1.750e+00   5.551 2.85e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 324.61  on 477  degrees of freedom
## Residual deviance: 264.00  on 473  degrees of freedom
## AIC: 274
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>In the next step we will compare how each model performed.</p>
</div>
</div>
<div id="evaluating-the-model-performance" class="section level1">
<h1><span class="header-section-number">3</span> Evaluating the model performance</h1>
<p>We started this step by making predictions using our model on the X’s variables in our Train and Test datasets.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">glm.prob.train<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">predict</span>(model_<span class="dv">1</span>, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb13-2" title="2">glm.prob.test<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">predict</span>(model_<span class="dv">1</span>, <span class="dt">newdata =</span> data.test, <span class="dt">type=</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb13-3" title="3"></a>
<a class="sourceLine" id="cb13-4" title="4">glm.prob.train<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">predict</span>(model_<span class="dv">2</span>, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb13-5" title="5">glm.prob.test<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">predict</span>(model_<span class="dv">2</span>, <span class="dt">newdata =</span> data.test, <span class="dt">type=</span> <span class="st">&quot;response&quot;</span>)</a></code></pre></div>
<p>We then evaluate the metrics in the each model for Train and Test data:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">glm.train<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">HMeasure</span>(data.train<span class="op">$</span>y_loan_defaulter, glm.prob.train<span class="fl">.1</span>, <span class="dt">threshold =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb14-2" title="2">glm.test<span class="fl">.1</span>  &lt;-<span class="st"> </span><span class="kw">HMeasure</span>(data.test<span class="op">$</span>y_loan_defaulter, glm.prob.test<span class="fl">.1</span>, <span class="dt">threshold =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb14-3" title="3"></a>
<a class="sourceLine" id="cb14-4" title="4">glm.train<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">HMeasure</span>(data.train<span class="op">$</span>y_loan_defaulter, glm.prob.train<span class="fl">.2</span>, <span class="dt">threshold =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb14-5" title="5">glm.test<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">HMeasure</span>(data.test<span class="op">$</span>y_loan_defaulter, glm.prob.test<span class="fl">.2</span>, <span class="dt">threshold =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb14-6" title="6"></a>
<a class="sourceLine" id="cb14-7" title="7">measures &lt;-<span class="st"> </span><span class="kw">t</span>(<span class="kw">bind_rows</span>(glm.train<span class="fl">.1</span><span class="op">$</span>metrics,</a>
<a class="sourceLine" id="cb14-8" title="8">                      glm.test<span class="fl">.1</span><span class="op">$</span>metrics,</a>
<a class="sourceLine" id="cb14-9" title="9">                      glm.train<span class="fl">.2</span><span class="op">$</span>metrics,</a>
<a class="sourceLine" id="cb14-10" title="10">                      glm.test<span class="fl">.2</span><span class="op">$</span>metrics)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as_tibble</span>(., <span class="dt">rownames =</span> <span class="ot">NA</span>)</a>
<a class="sourceLine" id="cb14-11" title="11"></a>
<a class="sourceLine" id="cb14-12" title="12"><span class="kw">colnames</span>(measures) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;model 1 - train&#39;</span>,<span class="st">&#39;model 1 - test&#39;</span>,</a>
<a class="sourceLine" id="cb14-13" title="13">                        <span class="st">&#39;model 2 - train&#39;</span>,<span class="st">&#39;model 2 - test&#39;</span>)</a>
<a class="sourceLine" id="cb14-14" title="14"></a>
<a class="sourceLine" id="cb14-15" title="15">measures<span class="op">$</span>metric =<span class="st"> </span><span class="kw">rownames</span>(measures)</a>
<a class="sourceLine" id="cb14-16" title="16"></a>
<a class="sourceLine" id="cb14-17" title="17">measures &lt;-<span class="st"> </span><span class="kw">select</span>(measures, metric, <span class="kw">everything</span>())</a>
<a class="sourceLine" id="cb14-18" title="18"></a>
<a class="sourceLine" id="cb14-19" title="19"><span class="kw">kable</span>(measures, <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">metric</th>
<th align="right">model 1 - train</th>
<th align="right">model 1 - test</th>
<th align="right">model 2 - train</th>
<th align="right">model 2 - test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">H</td>
<td align="right">0.3782094</td>
<td align="right">0.3436917</td>
<td align="right">0.3259694</td>
<td align="right">0.4267060</td>
</tr>
<tr class="even">
<td align="left">Gini</td>
<td align="right">0.6830601</td>
<td align="right">0.5642458</td>
<td align="right">0.6040777</td>
<td align="right">0.6420112</td>
</tr>
<tr class="odd">
<td align="left">AUC</td>
<td align="right">0.8415301</td>
<td align="right">0.7821229</td>
<td align="right">0.8020388</td>
<td align="right">0.8210056</td>
</tr>
<tr class="even">
<td align="left">AUCH</td>
<td align="right">0.8567066</td>
<td align="right">0.8179888</td>
<td align="right">0.8227029</td>
<td align="right">0.8521788</td>
</tr>
<tr class="odd">
<td align="left">KS</td>
<td align="right">0.5430959</td>
<td align="right">0.4563128</td>
<td align="right">0.5100335</td>
<td align="right">0.5450279</td>
</tr>
<tr class="even">
<td align="left">MER</td>
<td align="right">0.0962343</td>
<td align="right">0.0980392</td>
<td align="right">0.0941423</td>
<td align="right">0.1078431</td>
</tr>
<tr class="odd">
<td align="left">MWL</td>
<td align="right">0.0870958</td>
<td align="right">0.1169262</td>
<td align="right">0.0933982</td>
<td align="right">0.0978470</td>
</tr>
<tr class="even">
<td align="left">Spec.Sens95</td>
<td align="right">0.5035129</td>
<td align="right">0.3016760</td>
<td align="right">0.3161593</td>
<td align="right">0.3743017</td>
</tr>
<tr class="odd">
<td align="left">Sens.Spec95</td>
<td align="right">0.3921569</td>
<td align="right">0.4000000</td>
<td align="right">0.3333333</td>
<td align="right">0.4000000</td>
</tr>
<tr class="even">
<td align="left">ER</td>
<td align="right">0.1025105</td>
<td align="right">0.1176471</td>
<td align="right">0.0983264</td>
<td align="right">0.1176471</td>
</tr>
<tr class="odd">
<td align="left">Sens</td>
<td align="right">0.1764706</td>
<td align="right">0.1600000</td>
<td align="right">0.1568627</td>
<td align="right">0.1600000</td>
</tr>
<tr class="even">
<td align="left">Spec</td>
<td align="right">0.9836066</td>
<td align="right">0.9832402</td>
<td align="right">0.9906323</td>
<td align="right">0.9832402</td>
</tr>
<tr class="odd">
<td align="left">Precision</td>
<td align="right">0.5625000</td>
<td align="right">0.5714286</td>
<td align="right">0.6666667</td>
<td align="right">0.5714286</td>
</tr>
<tr class="even">
<td align="left">Recall</td>
<td align="right">0.1764706</td>
<td align="right">0.1600000</td>
<td align="right">0.1568627</td>
<td align="right">0.1600000</td>
</tr>
<tr class="odd">
<td align="left">TPR</td>
<td align="right">0.1764706</td>
<td align="right">0.1600000</td>
<td align="right">0.1568627</td>
<td align="right">0.1600000</td>
</tr>
<tr class="even">
<td align="left">FPR</td>
<td align="right">0.0163934</td>
<td align="right">0.0167598</td>
<td align="right">0.0093677</td>
<td align="right">0.0167598</td>
</tr>
<tr class="odd">
<td align="left">F</td>
<td align="right">0.2686567</td>
<td align="right">0.2500000</td>
<td align="right">0.2539683</td>
<td align="right">0.2500000</td>
</tr>
<tr class="even">
<td align="left">Youden</td>
<td align="right">0.1600771</td>
<td align="right">0.1432402</td>
<td align="right">0.1474951</td>
<td align="right">0.1432402</td>
</tr>
<tr class="odd">
<td align="left">TP</td>
<td align="right">9.0000000</td>
<td align="right">4.0000000</td>
<td align="right">8.0000000</td>
<td align="right">4.0000000</td>
</tr>
<tr class="even">
<td align="left">FP</td>
<td align="right">7.0000000</td>
<td align="right">3.0000000</td>
<td align="right">4.0000000</td>
<td align="right">3.0000000</td>
</tr>
<tr class="odd">
<td align="left">TN</td>
<td align="right">420.0000000</td>
<td align="right">176.0000000</td>
<td align="right">423.0000000</td>
<td align="right">176.0000000</td>
</tr>
<tr class="even">
<td align="left">FN</td>
<td align="right">42.0000000</td>
<td align="right">21.0000000</td>
<td align="right">43.0000000</td>
<td align="right">21.0000000</td>
</tr>
</tbody>
</table>
<p>Then, we look a boxplot chart to see how well our model split the observation into our explained variable:</p>
<p>-<strong>Model 1:</strong> <img src="02_logistic_regression_report_files/figure-html/boxplot_1-1.png" width="100%" /></p>
<p>-<strong>Model 2:</strong> <img src="02_logistic_regression_report_files/figure-html/boxplot_2-1.png" width="100%" /></p>
<p>Then we plot the ROC(Receiver Operator Characteristic Curve) of the model:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">roc_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">roc</span>(data.test<span class="op">$</span>y_loan_defaulter, glm.prob.test<span class="fl">.1</span>)</a>
<a class="sourceLine" id="cb15-2" title="2">roc_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">roc</span>(data.test<span class="op">$</span>y_loan_defaulter, glm.prob.test<span class="fl">.2</span>)</a>
<a class="sourceLine" id="cb15-3" title="3"></a>
<a class="sourceLine" id="cb15-4" title="4">y1 &lt;-<span class="st"> </span>roc_<span class="dv">1</span><span class="op">$</span>sensitivities</a>
<a class="sourceLine" id="cb15-5" title="5">x1 &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span>roc_<span class="dv">1</span><span class="op">$</span>specificities</a>
<a class="sourceLine" id="cb15-6" title="6"></a>
<a class="sourceLine" id="cb15-7" title="7">y2 &lt;-<span class="st"> </span>roc_<span class="dv">2</span><span class="op">$</span>sensitivities</a>
<a class="sourceLine" id="cb15-8" title="8">x2 &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span>roc_<span class="dv">2</span><span class="op">$</span>specificities</a>
<a class="sourceLine" id="cb15-9" title="9"></a>
<a class="sourceLine" id="cb15-10" title="10"><span class="kw">plot</span>(x1, y1,  <span class="dt">type=</span><span class="st">&quot;n&quot;</span>,</a>
<a class="sourceLine" id="cb15-11" title="11">     <span class="dt">xlab =</span> <span class="st">&quot;False Positive Rate (Specificities)&quot;</span>, </a>
<a class="sourceLine" id="cb15-12" title="12">     <span class="dt">ylab=</span> <span class="st">&quot;True Positive Rate (Sensitivities)&quot;</span>)</a>
<a class="sourceLine" id="cb15-13" title="13"></a>
<a class="sourceLine" id="cb15-14" title="14"><span class="kw">lines</span>(x1, y1,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>) </a>
<a class="sourceLine" id="cb15-15" title="15"><span class="kw">lines</span>(x2, y2,<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb15-16" title="16"></a>
<a class="sourceLine" id="cb15-17" title="17"><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="dt">lty=</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="02_logistic_regression_report_files/figure-html/roC-1.png" width="100%" /></p>
<p>By the ROC curve of each model we see that model 2 is a better model. It only condider the statistic significant variables.</p>
<p>Finally we look more closely to the model 2 accuracy:</p>
<p>-<strong>Model 2:</strong></p>
<p>To perform this task, we start by defining a threshold to assign the observation to each class, and them calculate the General Accuracy and the True Positive Rate. We start our analysis with a threshold of 0.5</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1">threshold &lt;-<span class="st"> </span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb16-2" title="2"></a>
<a class="sourceLine" id="cb16-3" title="3">fitted.results<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">ifelse</span>(glm.prob.test<span class="fl">.2</span> <span class="op">&gt;</span><span class="st"> </span>threshold ,<span class="dv">1</span> ,<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb16-4" title="4"></a>
<a class="sourceLine" id="cb16-5" title="5">misClasificError &lt;-<span class="st"> </span><span class="kw">mean</span>(fitted.results<span class="fl">.2</span> <span class="op">!=</span><span class="st"> </span>data.test<span class="op">$</span>y_loan_defaulter)</a>
<a class="sourceLine" id="cb16-6" title="6"></a>
<a class="sourceLine" id="cb16-7" title="7">misClassCount &lt;-<span class="st"> </span><span class="kw">misclassCounts</span>(fitted.results<span class="fl">.2</span>, data.test<span class="op">$</span>y_loan_defaulter)</a>
<a class="sourceLine" id="cb16-8" title="8"></a>
<a class="sourceLine" id="cb16-9" title="9"><span class="kw">paste</span>(<span class="st">&#39;Model General Accuracy of: &#39;</span>, <span class="kw">round</span>((<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>misClassCount<span class="op">$</span>metrics[<span class="st">&#39;ER&#39;</span>]) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">&#39;%&#39;</span>, <span class="dt">sep =</span> <span class="st">&#39;&#39;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Model General Accuracy of: 88.24%&quot;</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">paste</span>(<span class="st">&#39;True Positive Rate of    : &#39;</span>, <span class="kw">round</span>(misClassCount<span class="op">$</span>metrics[<span class="st">&#39;TPR&#39;</span>] <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">&#39;%&#39;</span>, <span class="dt">sep =</span> <span class="st">&#39;&#39;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;True Positive Rate of    : 16%&quot;</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="kw">kable</span>(misClassCount<span class="op">$</span>conf.matrix)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">pred.1</th>
<th align="right">pred.0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>actual.1</td>
<td align="right">4</td>
<td align="right">21</td>
</tr>
<tr class="even">
<td>actual.0</td>
<td align="right">3</td>
<td align="right">176</td>
</tr>
</tbody>
</table>
<p>At a first glance we may see this model as an excellent predictor of default as it can predict the correct class 88.24% of the cases.</p>
<p>But looking more closely at the confusion matrix we can see that this model can predict only 16% of the true defaulters.</p>
<p>One way to improve the performance of the model is to decrease the threshold to 0.2.</p>
<p>See results below:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1">threshold &lt;-<span class="st"> </span><span class="fl">0.2</span></a>
<a class="sourceLine" id="cb21-2" title="2"></a>
<a class="sourceLine" id="cb21-3" title="3">fitted.results<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">ifelse</span>(glm.prob.test<span class="fl">.2</span> <span class="op">&gt;</span><span class="st"> </span>threshold ,<span class="dv">1</span> ,<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb21-4" title="4"></a>
<a class="sourceLine" id="cb21-5" title="5">misClasificError &lt;-<span class="st"> </span><span class="kw">mean</span>(fitted.results<span class="fl">.2</span> <span class="op">!=</span><span class="st"> </span>data.test<span class="op">$</span>y_loan_defaulter)</a>
<a class="sourceLine" id="cb21-6" title="6"></a>
<a class="sourceLine" id="cb21-7" title="7">misClassCount &lt;-<span class="st"> </span><span class="kw">misclassCounts</span>(fitted.results<span class="fl">.2</span>, data.test<span class="op">$</span>y_loan_defaulter)</a>
<a class="sourceLine" id="cb21-8" title="8"></a>
<a class="sourceLine" id="cb21-9" title="9"><span class="kw">paste</span>(<span class="st">&#39;Model General Accuracy of: &#39;</span>, <span class="kw">round</span>((<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>misClassCount<span class="op">$</span>metrics[<span class="st">&#39;ER&#39;</span>]) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">&#39;%&#39;</span>, <span class="dt">sep =</span> <span class="st">&#39;&#39;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Model General Accuracy of: 86.76%&quot;</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw">paste</span>(<span class="st">&#39;True Positive Rate of    : &#39;</span>, <span class="kw">round</span>(misClassCount<span class="op">$</span>metrics[<span class="st">&#39;TPR&#39;</span>] <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">&#39;%&#39;</span>, <span class="dt">sep =</span> <span class="st">&#39;&#39;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;True Positive Rate of    : 52%&quot;</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="kw">kable</span>(misClassCount<span class="op">$</span>conf.matrix)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">pred.1</th>
<th align="right">pred.0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>actual.1</td>
<td align="right">13</td>
<td align="right">12</td>
</tr>
<tr class="even">
<td>actual.0</td>
<td align="right">15</td>
<td align="right">164</td>
</tr>
</tbody>
</table>
<p>Now we see that the True Positive accuracy increased to 52% and the general accuracy drop just a bit to 86.76%.</p>
<p>We may be tempted to reduce even more our threshold.</p>
<p>Let’s see what happen if we use 0.1 as threshold.</p>
<pre><code>## [1] &quot;Model General Accuracy of: 76.47%&quot;</code></pre>
<pre><code>## [1] &quot;True Positive Rate of    : 72%&quot;</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">pred.1</th>
<th align="right">pred.0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>actual.1</td>
<td align="right">18</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td>actual.0</td>
<td align="right">41</td>
<td align="right">138</td>
</tr>
</tbody>
</table>
<p>Now our TPR jumped to 72% and our general accuracy drop to 76.47%.</p>
<p>The final threshold will depend on the real word use case, by how much we value each class.</p>
<p>In this sample we see that we can improve our True Positive prediction rate at expense of classifying an increasing number as defaulter.</p>
<p>This balance must be decided by the managers and the bank should keep seeking and experimenting with more variables to find a better model.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
